
easy_admin:
    site_name: 'Demo Symfony Blog'
    entities:

        user:
            class: AppBundle\Entity\User
            form:
                fields:
                    - username
                    - email
                    - enabled
                    - lastLogin
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_AUTHOR': 'ROLE_AUTHOR', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        article:
            class: AppBundle\Entity\Article

            list:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'excerpt' }
                    - { property: 'date' }
                    - { property: 'categories' }
                    - { property: 'author' }
                    - { property: 'imageName', type: 'image', base_path: '%app.path.article_images%' }

            form:
                fields:
                    - { property: 'id' }
                    - { property: 'title' }
                    - { property: 'content', type: 'ckeditor' }
                    - { property: 'excerpt' }
                    - { property: 'date' }
                    - { property: 'categories' }
                    - { property: 'author' }
                    - { property: 'imageFile', type: 'vich_image' }

        article_category:
            class: AppBundle\Entity\ArticleCategory